;;
; @brief This file contains constants
;;


;;
; @def LED pin with pwm output
;;

RX     equ 0x01


;;
; @def LED pin with pwm output
;;

TX     equ 0x02


;;
; @def LED pin with pwm output
;;

LED     equ 0x03


;;
; @def MAX maximum value of the pointer
;;

MAX     equ 0xFE


;;
; @def SEND this byte cause the uart to send contineous
;;

SEND_CONTINEOUS equ 'C'


;;
; @def SEND this byte cause the uart to send one time
;;

SEND_SINGLE    equ 'S'


;;
; @def WAIT this byte disables the sending of the uart
;;

WAIT    equ 'W'

