;;
; @file
; @brief This file contains registeres used as variables
;;

        cblock 0x20
status_temp         ; 0x20
w_temp              ; 0x21
led                 ; 0x22
darker              ; 0x23
intensity_high      ; 0x24
intensity_low       ; 0x25
pointer             ; 0x26
pointer_min         ; 0x27
pointer_max         ; 0x28
pointer_sub_high    ; 0x29
pointer_sub_low     ; 0x2a
RandHi              ; 0x2b
RandLo              ; 0x2c
sCcounter           ; 0x2d
sCduration          ; 0x2e
sCflag              ; 0x2f
offset				; 0x30
        endc
