;;
; @file
; @brief This file contains registeres used as variables
;;

        cblock 0x20
status_temp         ; 0x20
w_temp              ; 0x21
sCcounter           ; 0x22
sCduration          ; 0x23
sCflag              ; 0x24
RandHi              ; 0x25
RandLo              ; 0x26
received_byte       ; 0x27
darker              ; 0x28
pointer             ; 0x29
pointer_min         ; 0x2a
pointer_max         ; 0x2b
offset              ; 0x2c
intensity_high      ; 0x2d
intensity_low       ; 0x2e
        endc
