;;
; @file
; @brief This file contains registeres used as variables
;;

        cblock 0x20
status_temp         ; 0x20
w_temp              ; 0x21
sCcounter           ; 0x22
sCduration          ; 0x23
sCflag              ; 0x24
RandHi              ; 0x25
RandLo              ; 0x26
pointer_sub_high    ; 0x27
pointer_sub_low     ; 0x28
darker              ; 0x29
intensity_high      ; 0x2a
intensity_low       ; 0x2b
pointer             ; 0x2c
pointer_min         ; 0x2d
pointer_max         ; 0x2e
offset				; 0x2f
received_byte       ; 0x30
        endc
